name: NPM Check and eslint

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
                    cache: 'npm'
                    cache-dependency-path: '**/package-lock.json'

            -   name: npm install
                run: |
                    npm ci

            -   name: eslint
                run: |
                    npm run lint-ci
